# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20171207_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='shifts_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
