# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20171207_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='topic',
            new_name='shift',
        ),
        migrations.AlterField(
            model_name='run',
            name='message',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
