# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20171208_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='runs_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
