# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_run_runs_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
