# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20171208_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='runs_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='runs_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
